# Generated by Django 5.1.3 on 2024-11-22 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='educationaldetails',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_educationdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationaldetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='educationaldetails',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_educationdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_experiencedetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_experiencedetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_projectdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_projectdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_resumedetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_resumedetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_userdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_userdetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='created_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='created_userresumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='updated_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='updated_userresumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='languages',
            field=models.JSONField(),
        ),
    ]
